# Generated by Django 6.0.5 on 2026-06-03 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabkota',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alt_name', models.CharField(default='', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('provinsi', models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, related_name='kabkota', to='polls.provinsi')),
            ],
            options={
                'verbose_name_plural': 'Kabkota',
                'db_table': 'regencies',
            },
        ),
    ]
