# Generated by Django 6.0.5 on 2026-06-10 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_kabkota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namadata',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nama Data',
                'verbose_name_plural': 'Nama Data',
                'db_table': 'namadata',
            },
        ),
        migrations.CreateModel(
            name='Datprof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('jumlah', models.FloatField(verbose_name='Jumlah')),
                ('provinsi', models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, to='polls.provinsi', verbose_name='Provinsi')),
                ('namadata', models.ForeignKey(db_column='namadata_id', on_delete=django.db.models.deletion.CASCADE, to='polls.namadata', verbose_name='Nama Data')),
            ],
            options={
                'verbose_name': 'Data Provinsi',
                'verbose_name_plural': 'Data Provinsi',
                'db_table': 'data_province',
            },
        ),
    ]
