# Generated by Django 6.0.5 on 2026-06-03 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_kabkota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabkota',
            name='provinsi',
            field=models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, related_name='kabkota', to='polls.provinsi'),
        ),
    ]
